apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-price-api
  labels:
    app: car-price-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: car-price-api

  template:
    metadata:
      labels:
        app: car-price-api

    spec:
      containers:
      - name: car-price-container
        image: prathamesh0505/mlops:latest
        ports:
        - containerPort: 8000

        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-secret
              key: HF_TOKEN