apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: car-price-model
spec:
  predictor:
    sklearn:
      storageUri: https://huggingface.co/PG05/car-price-model/resolve/main/