name: Train Model

on:
  workflow_dispatch:
  push:
    paths:
      - training/**
      - data/**

jobs:
  train:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train model and upload
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python training/train.py